apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: shadowchats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: shadowchats/authentication:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: appsettings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: appsettings
          secret:
            secretName: authentication-secret
