apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
  namespace: shadowchats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
        - name: authentication-microservice
          image: shadowchats/authentication:latest
          volumeMounts:
            - name: appsettings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: appsettings
          secret:
            secretName: authentication-secret
