apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentication-postgres
  namespace: shadowchats
spec:
  instances: 2 # 1 Primary + 1 Standby
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: authentication
      owner: authentication
      passwordSecret:
        name: authentication-secret
        key: postgres-password
  monitoring:
    enablePodMonitor: true
