# Shadowchats — Copyright (C) 2025
# Dorovskoy Alexey Vasilievich (One290 / 0ne290) <lenya.dorovskoy@mail.ru>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the LICENSE file for details.
# For full copyright and authorship information, see the COPYRIGHT file.

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentication-postgres
  namespace: shadowchats
spec:
  instances: 2 # 1 Primary + 1 Standby
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: authentication
      owner: authentication
      passwordSecret:
        name: authentication-secret
        key: postgres-password
  monitoring:
    enablePodMonitor: true
