# Shadowchats — Copyright (C) 2025
# Dorovskoy Alexey Vasilievich (One290 / 0ne290) <lenya.dorovskoy@mail.ru>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the LICENSE file for details.
# For full copyright and authorship information, see the COPYRIGHT file.

apiVersion: v1
kind: Secret
metadata:
  name: authentication-secret
  namespace: shadowchats
type: Opaque
stringData:
  # Следите за тем, чтобы значения postgres-password и Password в строках подключения совпадали
  postgres-password: REPLACE_ME
  appsettings.json: |
    {
      "JwtSettings": {
        "SecretKeyBase64": "REPLACE_ME",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "PostgresConnectionStrings": {
        "ReadWrite": "Host=authentication-pgbouncer-rw.shadowchats.svc.cluster.local;Port=5432;Database=authentication;Username=authentication;Password=REPLACE_ME",
        "ReadOnly":  "Host=authentication-pgbouncer-ro.shadowchats.svc.cluster.local;Port=5432;Database=authentication;Username=authentication;Password=REPLACE_ME"
      }
    }
