apiVersion: v1
kind: Secret
metadata:
  name: authentication-secret
  namespace: shadowchats
type: Opaque
stringData:
  # Следите за тем, чтобы значения postgres-password и Password в строках подключения совпадали
  postgres-password: REPLACE_ME
  appsettings.json: |
    {
      "JwtSettings": {
        "SecretKeyBase64": "REPLACE_ME",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "PostgresConnectionStrings": {
        "ReadWrite": "Host=authentication-pgbouncer-rw.shadowchats.svc.cluster.local;Port=5432;Database=authentication;Username=authentication;Password=REPLACE_ME",
        "ReadOnly":  "Host=authentication-pgbouncer-ro.shadowchats.svc.cluster.local;Port=5432;Database=authentication;Username=authentication;Password=REPLACE_ME"
      }
    }
