apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: shadowchats
spec:
  selector:
    app: authentication
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  type: ClusterIP
