apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: shadowchats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentication-pdb
  namespace: shadowchats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: authentication
