# Shadowchats — Copyright (C) 2025
# Dorovskoy Alexey Vasilievich (One290 / 0ne290) <lenya.dorovskoy@mail.ru>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the LICENSE file for details.
# For full copyright and authorship information, see the COPYRIGHT file.

apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: shadowchats
type: Opaque
stringData:
  appsettings.json: |
    {
      "Kubernetes": {
        "Namespace": "shadowchats",
        "ServiceNames": [
          "authentication"
        ]
      },
      "JwtSettings": {
        "SecretKeyBase64": "REPLACE_ME",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "ReverseProxy": {
        "Routes": {
          "authentication-routes": {
            "ClusterId": "authentication",
            "Match": {
              "Path": "/authentication/{**catch-all}"
            },
            "AuthorizationPolicy": "AccountPolicy",
            "Transforms": [
              {
                "PathRemovePrefix": "/authentication",
                "RequestHeader": "X-Account-Id",
                "Set": "{Sub}"
              }
            ]
          }
        },
        "Clusters": {
          "authentication": {
            "LoadBalancingPolicy": "LeastRequests",
            "HealthCheck": {
              "Active": {
                "Enabled": true,
                "Interval": "00:00:10",
                "Timeout": "00:00:05",
                "Policy": "ConsecutiveFailures",
                "FailureThreshold": 2,
                "Path": "/health"
              },
              "Passive": {
                "Enabled": true,
                "Policy": "TransportFailureRate",
                "ReactivationPeriod": "00:02:00"
              }
            },
            "HttpRequest": {
              "Version": "2",
              "VersionPolicy": "RequestVersionExact",
              "AllowResponseBuffering": false,
              "RequestTimeout": "00:00:30"
            }
          }
        }
      }
    }
