apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: shadowchats
type: Opaque
stringData:
  appsettings.json: |
    {
      "Kubernetes": {
        "Namespace": "shadowchats",
        "ServiceNames": [
          "authentication-service"
        ]
      },
      "JwtSettings": {
        "SecretKeyBase64": "REPLACE_ME",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "ReverseProxy": {
        "Routes": {
          "authentication-routes": {
            "ClusterId": "authentication-service",
            "Match": {
              "Path": "/authentication/{**catch-all}"
            },
            "AuthorizationPolicy": "AccountPolicy",
            "Transforms": [
              {
                "RequestHeader": "X-Account-Id",
                "Set": "{Sub}"
              }
            ]
          }
        },
        "Clusters": {
          "authentication-service": {
            "LoadBalancingPolicy": "LeastRequests",
            "HealthCheck": {
              "Active": {
                "Enabled": true,
                "Interval": "00:00:10",
                "Timeout": "00:00:05",
                "Policy": "ConsecutiveFailures",
                "FailureThreshold": 2,
                "Path": "/health"
              },
              "Passive": {
                "Enabled": true,
                "Policy": "TransportFailureRate",
                "ReactivationPeriod": "00:02:00"
              }
            },
            "HttpRequest": {
              "Version": "2",
              "VersionPolicy": "RequestVersionExact",
              "AllowResponseBuffering": false,
              "RequestTimeout": "00:00:30"
            }
          }
        }
      }
    }
