apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shadowchats/deploy.git
    targetRevision: HEAD
    path: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
