apiVersion: batch/v1
kind: Job
metadata:
  name: authentication-migrate
  namespace: shadowchats
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: vault-agent
          image: hashicorp/vault:1.17.6
          args: ["vault", "agent", "-config=/vault/config/vault-agent.hcl"]
          volumeMounts:
            - name: vault-agent-config
            mountPath: /vault/config
      containers:
        - name: migrate
          image: one290/shadowchats:authentication-v0.0.0
          command: ["dotnet", "Shadowchats.Authentication.Presentation.dll", "migrate"]
      volumes:
        - name: vault-agent-config
          configMap:
            name: vault-agent-authentication-init
